# Generated by Django 5.0.13 on 2026-03-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_question_answer_quiz_quizquestion_quizquestionanswer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="createAt",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="isDelete",
            new_name="is_delete",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="isPublic",
            new_name="is_public",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="updateAt",
            new_name="update_at",
        ),
    ]
