# Generated by Django 5.0.13 on 2026-03-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_createat_set_create_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="set",
            name="created",
        ),
        migrations.RemoveField(
            model_name="set",
            name="modified",
        ),
        migrations.AlterModelTable(
            name="quizquestion",
            table="quizzes_question",
        ),
        migrations.AlterModelTable(
            name="quizquestionanswer",
            table="quizzes_question_answer",
        ),
        migrations.AlterModelTable(
            name="quizshare",
            table="quizzes_share",
        ),
        migrations.AlterModelTable(
            name="setshare",
            table="sets_share",
        ),
        migrations.AlterModelTable(
            name="testanswer",
            table="tests_answer",
        ),
    ]
