# Generated by Django 5.0.13 on 2026-03-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_is_delete_set_is_deleted_remove_set_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
