# Generated by Django 5.0.13 on 2026-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_create_at_set_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="is_public",
            new_name="is_published",
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Single Choice"),
                    ("text", "Text Fill"),
                    ("checkbox", "Check Box"),
                ],
                max_length=20,
            ),
        ),
    ]
