# Generated by Django 5.0.13 on 2026-03-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_is_public_quiz_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Single Choice"),
                    ("text", "Text Fill"),
                    ("checkbox", "Check Box"),
                ],
                max_length=20,
            ),
        ),
    ]
