# Generated by Django 5.0.13 on 2026-03-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_quizquestion_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="text_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="time_spent",
            field=models.IntegerField(default=0, help_text="seconds"),
        ),
        migrations.AlterField(
            model_name="testanswer",
            name="selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.quizquestionanswer",
            ),
        ),
    ]
