# Generated by Django 5.0.13 on 2026-03-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_testanswer_text_answer_alter_test_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="selected_answers",
            field=models.ManyToManyField(
                blank=True,
                related_name="multiple_test_answer",
                to="core.quizquestionanswer",
            ),
        ),
        migrations.AlterField(
            model_name="testanswer",
            name="selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="single_test_answer",
                to="core.quizquestionanswer",
            ),
        ),
    ]
