# Generated by Django 5.0.13 on 2026-03-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_testanswer_selected_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.question",
            ),
        ),
    ]
