# Generated by Django 5.0.13 on 2026-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_quizquestion_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="current_session_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("checkbox", "Checkbox"),
                    ("text", "Text"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("checkbox", "Checkbox"),
                    ("text", "Text"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
