# Generated by Django 5.0.13 on 2026-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_test_current_session_start_alter_question_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
