# Generated by Django 5.0.13 on 2026-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_user_username_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
