# Generated by Django 5.0.13 on 2026-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_user_otp_user_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
