# Generated by Django 5.0.13 on 2026-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_quiz_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allow_resuming",
            field=models.BooleanField(default=True),
        ),
    ]
