# Generated by Django 5.0.13 on 2026-04-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_aichatconversation_aichatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aichatconversation",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to="core.quiz",
            ),
        ),
    ]
