# Generated by Django 5.0.13 on 2026-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_aichatconversation_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aichatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")], max_length=10
            ),
        ),
    ]
