# Generated by Django 5.0.13 on 2026-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_aichatmessage_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
